# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx2G -XX:MaxMetaspaceSize=512m
org.gradle.parallel=true

# Fabric Properties
# check these on https://fabricmc.net/develop
minecraft_version=1.21.1
loader_version=0.19.5
fabric_kotlin_version=1.14.1+kotlin.2.4.20

# Mod Properties
mod_version=1.8.0+1.21.1
maven_group=com.github.mystery2099
archives_base_name=voxlib

# Dependencies
fabric_version=0.116.17+1.21.1
caffeine_version=3.2.4
modmenu_version=11.0.4
jmh_version=1.37

# NeoForge
neoforge_version=21.1.250
