modLoader="javafml"
loaderVersion="[2,)"
license="MMPL-1.0.1"
issueTrackerURL="https://github.com/Mystery2099/VoxLib/issues"

[[mods]]
modId="voxlib"
version="${version}"
displayName="Mystery2099's VoxLib"
displayURL="https://github.com/Mystery2099/VoxLib"
logoFile="assets/voxlib/icon.png"
authors="Mystery2099"
description="A library for creating, combining, transforming, debugging, and reusing voxel shapes."

[[dependencies.voxlib]]
modId="neoforge"
mandatory=true
versionRange="[20.6,)"
ordering="NONE"
side="BOTH"

[[dependencies.voxlib]]
modId="minecraft"
mandatory=true
versionRange="[1.20.5,1.21)"
ordering="NONE"
side="BOTH"
